version: '3'
services:
    master:
        image: greenbirdit/locust:0.9.0
        environment:
            - "LOCUST_MODE=master"
            - "TARGET_HOST=http://site.example.com"
            - "LOCUST_SCRIPT=/locust-tasks/tasks.py"
        volumes:
            - ./app/locust-tasks/tasks.py:/locust-tasks/tasks.py
        networks:
            locust-nw:
        ports:
            - "8089:8089"
    worker:
        image: greenbirdit/locust:0.9.0
        environment:
            - "LOCUST_MODE=worker"
            - "LOCUST_MASTER=master"
            - "LOCUST_MASTER_WEB=8089"
            - "TARGET_HOST=http://site.example.com"
            - "LOCUST_SCRIPT=/locust-tasks/tasks.py"
        volumes:
            - ./app/locust-tasks/tasks.py:/locust-tasks/tasks.py
        networks:
            locust-nw:

networks:
    locust-nw:
